#include "views/preferencesdialog.h"
#include <libnick/localization/gettext.h>

using namespace Nickvision::Events;
using namespace Nickvision::TubeConverter::Shared::Controllers;
using namespace Nickvision::TubeConverter::Shared::Models;

namespace Nickvision::TubeConverter::GNOME::Views
{
    PreferencesDialog::PreferencesDialog(const std::shared_ptr<PreferencesViewController>& controller, GtkWindow* parent)
        : DialogBase{ parent, "preferences_dialog" },
        m_controller{ controller }
    {
        //Load
        DownloaderOptions options{ m_controller->getDownloaderOptions() };
        adw_combo_row_set_selected(ADW_COMBO_ROW(gtk_builder_get_object(m_builder, "themeRow")), static_cast<unsigned int>(m_controller->getTheme()));
        adw_combo_row_set_selected(ADW_COMBO_ROW(gtk_builder_get_object(m_builder, "completedNotificationTriggerRow")), static_cast<unsigned int>(m_controller->getCompletedNotificationPreference()));
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "preventSuspendRow")), m_controller->getPreventSuspend());
        adw_combo_row_set_selected(ADW_COMBO_ROW(gtk_builder_get_object(m_builder, "historyLengthRow")), static_cast<unsigned int>(m_controller->getHistoryLengthIndex()));
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "overwriteExistingFilesRow")), options.getOverwriteExistingFiles());
        adw_spin_row_set_value(ADW_SPIN_ROW(gtk_builder_get_object(m_builder, "maxNumberOfActiveDownloadsRow")), static_cast<double>(options.getMaxNumberOfActiveDownloads()));
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "limitCharactersRow")), options.getLimitCharacters());
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "includeAutoGeneratedSubtitlesRow")), options.getIncludeAutoGeneratedSubtitles());
        adw_spin_row_set_value(ADW_SPIN_ROW(gtk_builder_get_object(m_builder, "speedLimitRow")), static_cast<double>(options.getSpeedLimit()));
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "sponsorBlockRow")), options.getYouTubeSponsorBlock());
        gtk_editable_set_text(GTK_EDITABLE(gtk_builder_get_object(m_builder, "proxyUrlRow")), options.getProxyUrl().c_str());
        adw_combo_row_set_selected(ADW_COMBO_ROW(gtk_builder_get_object(m_builder, "cookiesBrowserRow")), static_cast<unsigned int>(options.getCookiesBrowser()));
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "embedMetadataRow")), options.getEmbedMetadata());
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "embedChaptersRow")), options.getEmbedChapters());
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "embedSubtitlesRow")), options.getEmbedSubtitles());
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "cropAudioThumbnailRow")), options.getCropAudioThumbnails());
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "removeSourceDataRow")), options.getRemoveSourceData());
        adw_switch_row_set_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "useAriaRow")), options.getUseAria());
        adw_spin_row_set_value(ADW_SPIN_ROW(gtk_builder_get_object(m_builder, "ariaMaxConnectionsPerServerRow")), static_cast<double>(options.getAriaMaxConnectionsPerServer()));
        adw_spin_row_set_value(ADW_SPIN_ROW(gtk_builder_get_object(m_builder, "ariaMinSplitSizeRow")), static_cast<double>(options.getAriaMinSplitSize()));
        //Signals
        m_closed += [&](const EventArgs&) { onClosed(); };
        g_signal_connect(gtk_builder_get_object(m_builder, "themeRow"), "notify::selected-item", G_CALLBACK(+[](GObject*, GParamSpec* pspec, gpointer data){ reinterpret_cast<PreferencesDialog*>(data)->onThemeChanged(); }), this);
    }

    void PreferencesDialog::onClosed()
    {
        DownloaderOptions options{ m_controller->getDownloaderOptions() };
        m_controller->setCompletedNotificationPreference(static_cast<CompletedNotificationPreference>(adw_combo_row_get_selected(ADW_COMBO_ROW(gtk_builder_get_object(m_builder, "completedNotificationTriggerRow")))));
        m_controller->setPreventSuspend(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "preventSuspendRow"))));
        m_controller->setHistoryLengthIndex(static_cast<size_t>(adw_combo_row_get_selected(ADW_COMBO_ROW(gtk_builder_get_object(m_builder, "historyLengthRow")))));
        options.setOverwriteExistingFiles(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "overwriteExistingFilesRow"))));
        options.setMaxNumberOfActiveDownloads(static_cast<int>(adw_spin_row_get_value(ADW_SPIN_ROW(gtk_builder_get_object(m_builder, "maxNumberOfActiveDownloadsRow")))));
        options.setLimitCharacters(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "limitCharactersRow"))));
        options.setIncludeAutoGeneratedSubtitles(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "includeAutoGeneratedSubtitlesRow"))));
        options.setSpeedLimit(static_cast<int>(adw_spin_row_get_value(ADW_SPIN_ROW(gtk_builder_get_object(m_builder, "speedLimitRow")))));
        options.setYouTubeSponsorBlock(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "sponsorBlockRow"))));
        options.setProxyUrl(gtk_editable_get_text(GTK_EDITABLE(gtk_builder_get_object(m_builder, "proxyUrlRow"))));
        options.setCookiesBrowser(static_cast<CookiesBrowser>(adw_combo_row_get_selected(ADW_COMBO_ROW(gtk_builder_get_object(m_builder, "cookiesBrowserRow")))));
        options.setEmbedMetadata(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "embedMetadataRow"))));
        options.setEmbedChapters(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "embedChaptersRow"))));
        options.setEmbedSubtitles(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "embedSubtitlesRow"))));
        options.setCropAudioThumbnails(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "cropAudioThumbnailRow"))));
        options.setRemoveSourceData(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "removeSourceDataRow"))));
        options.setUseAria(adw_switch_row_get_active(ADW_SWITCH_ROW(gtk_builder_get_object(m_builder, "useAriaRow"))));
        options.setAriaMaxConnectionsPerServer(static_cast<int>(adw_spin_row_get_value(ADW_SPIN_ROW(gtk_builder_get_object(m_builder, "ariaMaxConnectionsPerServerRow")))));
        options.setAriaMinSplitSize(static_cast<int>(adw_spin_row_get_value(ADW_SPIN_ROW(gtk_builder_get_object(m_builder, "ariaMinSplitSizeRow")))));
        m_controller->setDownloaderOptions(options);
        m_controller->saveConfiguration();
    }

    void PreferencesDialog::onThemeChanged()
    {
        m_controller->setTheme(static_cast<Theme>(adw_combo_row_get_selected(ADW_COMBO_ROW(gtk_builder_get_object(m_builder, "themeRow")))));
        switch (m_controller->getTheme())
        {
        case Theme::Light:
            adw_style_manager_set_color_scheme(adw_style_manager_get_default(), ADW_COLOR_SCHEME_FORCE_LIGHT);
            break;
        case Theme::Dark:
            adw_style_manager_set_color_scheme(adw_style_manager_get_default(), ADW_COLOR_SCHEME_FORCE_DARK);
            break;
        default:
            adw_style_manager_set_color_scheme(adw_style_manager_get_default(), ADW_COLOR_SCHEME_DEFAULT);
            break;
        }
    }
}
