namespace Nickvision.TubeConverter.WinUI.Controls
{
    [default_interface]
    runtimeclass DownloadRow : Microsoft.UI.Xaml.Controls.UserControl
    {
        DownloadRow();
        event Microsoft.UI.Xaml.RoutedEventHandler PauseRequested;
        event Microsoft.UI.Xaml.RoutedEventHandler ResumeRequested;
        event Microsoft.UI.Xaml.RoutedEventHandler StopRequested;
        event Microsoft.UI.Xaml.RoutedEventHandler RetryRequested;
    }
}
