namespace Nickvision.TubeConverter.WinUI.Controls
{
    [default_interface]
    runtimeclass SettingsRow : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsRow();
        static Microsoft.UI.Xaml.DependencyProperty GlyphProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty TitleProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ChildProperty{ get; };
        String Glyph;
        String Title;
        String Description;
        Object Child;
        Microsoft.UI.Xaml.Visibility IconVisibility{ get; };
        Microsoft.UI.Xaml.Visibility TitleVisibility{ get; };
        Microsoft.UI.Xaml.Visibility DescriptionVisibility{ get; };
    }
}