namespace Nickvision.TubeConverter.WinUI.Controls
{
    [default_interface]
    runtimeclass StatusPage : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        StatusPage();
        static Microsoft.UI.Xaml.DependencyProperty GlyphProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty UseAppIconProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty TitleProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ChildProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty IsCompactProperty{ get; };
        String Glyph;
        Boolean UseAppIcon;
        String Title;
        String Description;
        Object Child;
        Boolean IsCompact;
        Microsoft.UI.Xaml.Visibility GlyphIconVisibility{ get; };
        Microsoft.UI.Xaml.Visibility AppIconVisibility{ get; };
        Microsoft.UI.Xaml.Visibility TitleVisibility{ get; };
        Microsoft.UI.Xaml.Visibility DescriptionVisibility{ get; };
        Microsoft.UI.Xaml.Visibility ChildVisibility{ get; };
        Double CompactSpacing{ get; };
        Double IconSize{ get; };
        Double IconWidth{ get; };
        Double IconHeight{ get; };
        Microsoft.UI.Xaml.Style TitleStyle{ get; };
    }
}
