namespace Nickvision.TubeConverter.WinUI.Controls
{
    [default_interface]
    runtimeclass ViewStack : Microsoft.UI.Xaml.Controls.UserControl
    {
        ViewStack();
        static Microsoft.UI.Xaml.DependencyProperty PagesProperty{ get; };
        Int32 CurrentPageIndex;
        IObservableVector<Object> Pages{ get; };
    }
}
