using Nickvision.Desktop.Application;
using Nickvision.Parabolic.Shared.Models;
using System;
using System.Collections.Generic;

namespace Nickvision.Parabolic.Shared.Helpers;

public static class IConfigurationServiceExtensions
{
    extension(IConfigurationService configurationService)
    {
        public bool AllowPreviewUpdates
        {
            get => configurationService.Get("AllowPreviewUpdates", false);

            set => configurationService.Set("AllowPreviewUpdates", value);
        }

        public int AriaMaxConnectionsPerServer
        {
            get => configurationService.Get("AriaMaxConnectionsPerServer", 16);

            set => configurationService.Set("AriaMaxConnectionsPerServer", value);
        }

        public int AriaMinSplitSize
        {
            get => configurationService.Get("AriaMinSplitSize", 20);

            set => configurationService.Set("AriaMinSplitSize", value);
        }

        public Browser CookiesBrowser
        {
            get => (Browser)configurationService.Get("CookiesBrowser", (int)Browser.None);

            set => configurationService.Set("CookiesBrowser", (int)value);
        }

        public string CookiesPath
        {
            get => configurationService.Get("CookiesPath", string.Empty);

            set => configurationService.Set("CookiesPath", value);
        }

        public bool CropAudioThumbnails
        {
            get => configurationService.Get("CropAudioThumbnails", false);

            set => configurationService.Set("CropAudioThumbnails", value);
        }

        public bool EmbedChapters
        {
            get => configurationService.Get("EmbedChapters", false);

            set => configurationService.Set("EmbedChapters", value);
        }

        public bool EmbedMetadata
        {
            get => configurationService.Get("EmbedMetadata", true);

            set => configurationService.Set("EmbedMetadata", value);
        }

        public bool EmbedSubtitles
        {
            get => configurationService.Get("EmbedSubtitles", true);

            set => configurationService.Set("EmbedSubtitles", value);
        }

        public bool EmbedThumbnails
        {
            get => configurationService.Get("EmbedThumbnails", true);

            set => configurationService.Set("EmbedThumbnails", value);
        }

        public bool IncludeAutoGeneratedSubtitles
        {
            get => configurationService.Get("IncludeAutoGeneratedSubtitles", true);

            set => configurationService.Set("IncludeAutoGeneratedSubtitles", value);
        }

        public bool IncludeMediaIdInTitle
        {
            get => configurationService.Get("IncludeMediaIdInTitle", true);

            set => configurationService.Set("IncludeMediaIdInTitle", value);
        }

        public bool IncludeSuperResolutions
        {
            get => configurationService.Get("IncludeSuperResolutions", true);

            set => configurationService.Set("IncludeSuperResolutions", value);
        }

        public bool LimitCharacters
        {
            get => configurationService.Get("LimitCharacters", OperatingSystem.IsWindows());

            set => configurationService.Set("LimitCharacters", value);
        }

        public int MaxNumberOfActiveDownloads
        {
            get => configurationService.Get("MaxNumberOfActiveDownloads", 5);

            set => configurationService.Set("MaxNumberOfActiveDownloads", value);
        }

        public bool OverwriteExistingFiles
        {
            get => configurationService.Get("OverwriteExistingFiles", true);

            set => configurationService.Set("OverwriteExistingFiles", value);
        }

        public int PostprocessingThreads
        {
            get => configurationService.Get("PostprocessingThreads", Environment.ProcessorCount);

            set => configurationService.Set("PostprocessingThreads", value);
        }

        public List<PostProcessorArgument> PostprocessingArguments
        {
            get => configurationService.Get("PostprocessingArguments", new List<PostProcessorArgument>());

            set => configurationService.Set("PostprocessingArguments", value);
        }

        public AudioCodec PreferredAudioCodec
        {
            get => (AudioCodec)configurationService.Get("PreferredAudioCodec", (int)AudioCodec.Any);

            set => configurationService.Set("PreferredAudioCodec", (int)value);
        }

        public FrameRate PreferredFrameRate
        {
            get => (FrameRate)configurationService.Get("PreferredFrameRate", (int)FrameRate.Any);

            set => configurationService.Set("PreferredFrameRate", (int)value);
        }

        public SubtitleFormat PreferredSubtitleFormat
        {
            get => (SubtitleFormat)configurationService.Get("PreferredSubtitleFormat", (int)SubtitleFormat.Any);

            set => configurationService.Set("PreferredSubtitleFormat", (int)value);
        }

        public VideoCodec PreferredVideoCodec
        {
            get => (VideoCodec)configurationService.Get("PreferredVideoCodec", (int)VideoCodec.Any);

            set => configurationService.Set("PreferredVideoCodec", (int)value);
        }

        public bool PreventSuspend
        {
            get => configurationService.Get("PreventSuspend", false);

            set => configurationService.Set("PreventSuspend", value);
        }

        public string ProxyUrl
        {
            get => configurationService.Get("ProxyUrl", string.Empty);

            set => configurationService.Set("ProxyUrl", value);
        }

        public bool RemoveSourceData
        {
            get => configurationService.Get("RemoveSourceData", false);

            set => configurationService.Set("RemoveSourceData", value);
        }

        public bool ShowDisclaimerOnStartup
        {
            get => configurationService.Get("ShowDisclaimerOnStartup", true);

            set => configurationService.Set("ShowDisclaimerOnStartup", value);
        }

        public int? SpeedLimit
        {
            get
            {
                var limit = configurationService.Get("SpeedLimit", string.Empty);
                if(int.TryParse(limit, out var result))
                {
                    return result;
                }
                else
                {
                    return null;
                }
            }

            set => configurationService.Set("SpeedLimit", value.HasValue ? value.Value.ToString() : string.Empty);
        }

        public Theme Theme
        {
            get => (Theme)configurationService.Get("Theme", 2);

            set => configurationService.Set("Theme", (int)value);
        }

        public bool TranslateMetadataAndChapters
        {
            get => configurationService.Get("TranslateMetadataAndChapters", true);

            set => configurationService.Set("TranslateMetadataAndChapters", value);
        }

        public string TranslationLanguage
        {
            get => configurationService.Get("TranslationLanguage", string.Empty);

            set => configurationService.Set("TranslationLanguage", value);
        }

        public bool UseAria
        {
            get => configurationService.Get("UseAria", false);

            set => configurationService.Set("UseAria", value);
        }

        public bool UsePartFiles
        {
            get => configurationService.Get("UsePartFiles", true);

            set => configurationService.Set("UsePartFiles", value);
        }

        public WindowGeometry WindowGeometry
        {
            get => configurationService.Get("WindowGeometry", new WindowGeometry(), ApplicationJsonContext.Default.WindowGeometry);

            set => configurationService.Set("WindowGeometry", value, ApplicationJsonContext.Default.WindowGeometry);
        }

        public bool YouTubeSponsorBlock
        {
            get => configurationService.Get("YouTubeSponsorBlock", false);

            set => configurationService.Set("YouTubeSponsorBlock", value);
        }

        public string YtdlpDiscoveryArgs
        {
            get => configurationService.Get("YtdlpDiscoveryArgs", string.Empty);

            set => configurationService.Set("YtdlpDiscoveryArgs", value);
        }

        public string YtdlpDownloadArgs
        {
            get => configurationService.Get("YtdlpDownloadArgs", string.Empty);

            set => configurationService.Set("YtdlpDownloadArgs", value);
        }
    }
}
