using Nickvision.Desktop.Application;
using Nickvision.Desktop.Converters;
using Nickvision.Parabolic.Shared.Helpers;
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Nickvision.Parabolic.Shared.Models;

public class Configuration
{
    public static readonly string Key;

    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool PreventSuspend { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool OverwriteExistingFiles { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool LimitCharacters { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool IncludeMediaIdInTitle { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool IncludeAutoGeneratedSubtitles { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool IncludeSuperResolutions { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<VideoCodec>))]
    public VideoCodec PreferredVideoCodec { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<AudioCodec>))]
    public AudioCodec PreferredAudioCodec { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<SubtitleFormat>))]
    public SubtitleFormat PreferredSubtitleFormat { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<FrameRate>))]
    public FrameRate PreferredFrameRate { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool UsePartFiles { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool YouTubeSponsorBlock { get; set; }
    public int? SpeedLimit { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string ProxyUrl { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<Browser>))]
    public Browser CookiesBrowser { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string CookiesPath { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool TranslateMetadataAndChapters { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool EmbedMetadata { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool RemoveSourceData { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool EmbedThumbnails { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool CropAudioThumbnails { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool EmbedChapters { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool EmbedSubtitles { get; set; }
    [JsonConverter(typeof(NullToDefaultObjectConverter<List<PostProcessorArgument>>))]
    public List<PostProcessorArgument> PostprocessingArguments { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool UseAria { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string YtdlpDiscoveryArgs { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string YtdlpDownloadArgs { get; set; }

    static Configuration()
    {
        Key = "config";
    }

    public Configuration()
    {
        PreventSuspend = false;
        MaxNumberOfActiveDownloads = 5;
        OverwriteExistingFiles = true;
        LimitCharacters = OperatingSystem.IsWindows();
        IncludeMediaIdInTitle = true;
        IncludeAutoGeneratedSubtitles = true;
        IncludeSuperResolutions = true;
        PreferredVideoCodec = VideoCodec.Any;
        PreferredAudioCodec = AudioCodec.Any;
        PreferredSubtitleFormat = SubtitleFormat.Any;
        PreferredFrameRate = FrameRate.Any;
        UsePartFiles = true;
        YouTubeSponsorBlock = false;
        SpeedLimit = null;
        ProxyUrl = string.Empty;
        CookiesBrowser = Browser.None;
        CookiesPath = string.Empty;
        TranslateMetadataAndChapters = true;
        EmbedMetadata = true;
        RemoveSourceData = false;
        EmbedThumbnails = true;
        CropAudioThumbnails = false;
        EmbedChapters = false;
        EmbedSubtitles = true;
        PostprocessingThreads = Environment.ProcessorCount;
        PostprocessingArguments = new List<PostProcessorArgument>();
        UseAria = false;
        AriaMaxConnectionsPerServer = 16;
        AriaMinSplitSize = 20;
        YtdlpDiscoveryArgs = string.Empty;
        YtdlpDownloadArgs = string.Empty;
    }

    [JsonConverter(typeof(NullToZeroIntConverter))]
    public int MaxNumberOfActiveDownloads
    {
        get => field == 0 ? 5 : field;

        set;
    }

    [JsonConverter(typeof(NullToZeroIntConverter))]
    public int PostprocessingThreads
    {
        get => field == 0 ? Environment.ProcessorCount : field;

        set;
    }

    [JsonConverter(typeof(NullToZeroIntConverter))]
    public int AriaMaxConnectionsPerServer
    {
        get => field == 0 ? 16 : field;

        set;
    }

    [JsonConverter(typeof(NullToZeroIntConverter))]
    public int AriaMinSplitSize
    {
        get => field == 0 ? 20 : field;

        set;
    }
}
