using Nickvision.Desktop.Application;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Nickvision.Parabolic.Shared.Models;

public class Configuration
{
    public static readonly string Key;

    public bool AllowPreviewUpdates { get; set; }
    public Theme Theme { get; set; }
    public string TranslationLanguage { get; set; }
    public WindowGeometry WindowGeometry { get; set; }
    public AppVersion InstalledYtdlpVersion { get; set; }
    public bool ShowDislcaimerOnStartup { get; set; }
    public bool PreventSuspend { get; set; }
    public int MaxNumberOfActiveDownloads { get; set; }
    public bool OverwriteExistingFiles { get; set; }
    public bool LimitCharacters { get; set; }
    public bool IncludeMediaIdInTitle { get; set; }
    public bool IncludeAutoGeneratedSubtitles { get; set; }
    public VideoCodec PreferredVideoCodec { get; set; }
    public AudioCodec PreferredAudioCodec { get; set; }
    public SubtitleFormat PreferredSubtitleFormat { get; set; }
    public bool UsePartFiles { get; set; }
    public bool YouTubeSponsorBlock { get; set; }
    public int? SpeedLimit { get; set; }
    public string ProxyUrl { get; set; }
    public Browser CookiesBrowser { get; set; }
    public string CookiesPath { get; set; }
    public bool EmbedMetadata { get; set; }
    public bool RemoveSourceData { get; set; }
    public bool EmbedThumbnails { get; set; }
    public bool CropAudioThumbnails { get; set; }
    public bool EmbedChapters { get; set; }
    public bool EmbedSubtitles { get; set; }
    public int PostprocessingThreads { get; set; }
    public List<PostProcessorArgument> PostprocessingArguments { get; set; }
    public bool UseAria { get; set; }
    public int AriaMaxConnectionsPerServer { get; set; }
    public int AriaMinSplitSize { get; set; }

    static Configuration()
    {
        Key = "config";
    }

    public Configuration()
    {
        Theme = Theme.System;
        TranslationLanguage = string.Empty;
        WindowGeometry = new WindowGeometry();
        AllowPreviewUpdates = false;
        InstalledYtdlpVersion = new AppVersion("0.0.0");
        ShowDislcaimerOnStartup = true;
        PreventSuspend = false;
        MaxNumberOfActiveDownloads = 5;
        OverwriteExistingFiles = true;
        LimitCharacters = OperatingSystem.IsWindows();
        IncludeMediaIdInTitle = true;
        IncludeAutoGeneratedSubtitles = true;
        PreferredVideoCodec = VideoCodec.Any;
        PreferredAudioCodec = AudioCodec.Any;
        PreferredSubtitleFormat = SubtitleFormat.Any;
        UsePartFiles = true;
        YouTubeSponsorBlock = false;
        SpeedLimit = null;
        ProxyUrl = string.Empty;
        CookiesBrowser = Browser.None;
        CookiesPath = string.Empty;
        EmbedMetadata = true;
        RemoveSourceData = false;
        EmbedThumbnails = true;
        CropAudioThumbnails = false;
        EmbedChapters = false;
        EmbedSubtitles = true;
        PostprocessingThreads = Environment.ProcessorCount;
        PostprocessingArguments = new List<PostProcessorArgument>();
        UseAria = false;
        AriaMaxConnectionsPerServer = 16;
        AriaMinSplitSize = 20;
    }

    [JsonIgnore]
    public DownloaderOptions DownloaderOptions => new DownloaderOptions()
    {
        MaxNumberOfActiveDownloads = MaxNumberOfActiveDownloads,
        OverwriteExistingFiles = OverwriteExistingFiles,
        LimitCharacters = LimitCharacters,
        IncludeMediaIdInTitle = IncludeMediaIdInTitle,
        IncludeAutoGeneratedSubtitles = IncludeAutoGeneratedSubtitles,
        PreferredVideoCodec = PreferredVideoCodec,
        PreferredAudioCodec = PreferredAudioCodec,
        PreferredSubtitleFormat = PreferredSubtitleFormat,
        UsePartFiles = UsePartFiles,
        YouTubeSponsorBlock = YouTubeSponsorBlock,
        SpeedLimit = SpeedLimit,
        ProxyUrl = ProxyUrl,
        CookiesBrowser = CookiesBrowser,
        CookiesPath = CookiesPath,
        EmbedMetadata = EmbedMetadata,
        RemoveSourceData = RemoveSourceData,
        EmbedThumbnails = EmbedThumbnails,
        CropAudioThumbnails = CropAudioThumbnails,
        EmbedChapters = EmbedChapters,
        EmbedSubtitles = EmbedSubtitles,
        PostprocessingThreads = PostprocessingThreads,
        PostprocessingArguments = PostprocessingArguments,
        UseAria = UseAria,
        AriaMaxConnectionsPerServer = AriaMaxConnectionsPerServer,
        AriaMinSplitSize = AriaMinSplitSize
    };
}
