using Nickvision.Desktop.Application;
using Nickvision.Desktop.Converters;
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Nickvision.Parabolic.Shared.Models;

public class Configuration
{
    private static readonly JsonSerializerOptions _options;

    public static readonly string Key;

    [JsonConverter(typeof(NullToDefaultValueConverter<Theme>))]
    public Theme Theme { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool AllowPreviewUpdates { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string TranslationLanguage { get; set; }
    [JsonConverter(typeof(NullToDefaultObjectConverter<WindowGeometry>))]
    public WindowGeometry WindowGeometry { get; set; }
    [JsonConverter(typeof(NullToDefaultObjectConverter<AppVersion>))]
    public AppVersion InstalledYtdlpAppVersion { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool ShowDislcaimerOnStartup { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool PreventSuspend { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool OverwriteExistingFiles { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool LimitCharacters { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool IncludeMediaIdInTitle { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool IncludeAutoGeneratedSubtitles { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<VideoCodec>))]
    public VideoCodec PreferredVideoCodec { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<AudioCodec>))]
    public AudioCodec PreferredAudioCodec { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<SubtitleFormat>))]
    public SubtitleFormat PreferredSubtitleFormat { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<FrameRate>))]
    public FrameRate PreferredFrameRate { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool UsePartFiles { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool YouTubeSponsorBlock { get; set; }
    public int? SpeedLimit { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string ProxyUrl { get; set; }
    [JsonConverter(typeof(NullToDefaultValueConverter<Browser>))]
    public Browser CookiesBrowser { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string CookiesPath { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool EmbedMetadata { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool RemoveSourceData { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool EmbedThumbnails { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool CropAudioThumbnails { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool EmbedChapters { get; set; }
    [JsonConverter(typeof(NullToTrueBoolConverter))]
    public bool EmbedSubtitles { get; set; }
    [JsonConverter(typeof(NullToDefaultObjectConverter<List<PostProcessorArgument>>))]
    public List<PostProcessorArgument> PostprocessingArguments { get; set; }
    [JsonConverter(typeof(NullToFalseBoolConverter))]
    public bool UseAria { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string YtdlpDiscoveryArgs { get; set; }
    [JsonConverter(typeof(NullToEmptyStringConverter))]
    public string YtdlpDownloadArgs { get; set; }

    static Configuration()
    {
        _options = new JsonSerializerOptions
        {
            WriteIndented = true
        };
        Key = "config";
    }

    public Configuration()
    {
        Theme = Theme.System;
        TranslationLanguage = string.Empty;
        WindowGeometry = new WindowGeometry();
        AllowPreviewUpdates = false;
        InstalledYtdlpAppVersion = new AppVersion("0.0.0");
        ShowDislcaimerOnStartup = true;
        PreventSuspend = false;
        MaxNumberOfActiveDownloads = 5;
        OverwriteExistingFiles = true;
        LimitCharacters = OperatingSystem.IsWindows();
        IncludeMediaIdInTitle = true;
        IncludeAutoGeneratedSubtitles = true;
        PreferredVideoCodec = VideoCodec.Any;
        PreferredAudioCodec = AudioCodec.Any;
        PreferredSubtitleFormat = SubtitleFormat.Any;
        PreferredFrameRate = FrameRate.Any;
        UsePartFiles = true;
        YouTubeSponsorBlock = false;
        SpeedLimit = null;
        ProxyUrl = string.Empty;
        CookiesBrowser = Browser.None;
        CookiesPath = string.Empty;
        EmbedMetadata = true;
        RemoveSourceData = false;
        EmbedThumbnails = true;
        CropAudioThumbnails = false;
        EmbedChapters = false;
        EmbedSubtitles = true;
        PostprocessingThreads = Environment.ProcessorCount;
        PostprocessingArguments = new List<PostProcessorArgument>();
        UseAria = false;
        AriaMaxConnectionsPerServer = 16;
        AriaMinSplitSize = 20;
        YtdlpDiscoveryArgs = string.Empty;
        YtdlpDownloadArgs = string.Empty;
    }

    [JsonIgnore]
    public DownloaderOptions DownloaderOptions => new DownloaderOptions()
    {
        MaxNumberOfActiveDownloads = MaxNumberOfActiveDownloads,
        OverwriteExistingFiles = OverwriteExistingFiles,
        LimitCharacters = LimitCharacters,
        IncludeMediaIdInTitle = IncludeMediaIdInTitle,
        IncludeAutoGeneratedSubtitles = IncludeAutoGeneratedSubtitles,
        PreferredVideoCodec = PreferredVideoCodec,
        PreferredAudioCodec = PreferredAudioCodec,
        PreferredSubtitleFormat = PreferredSubtitleFormat,
        PreferredFrameRate = PreferredFrameRate,
        UsePartFiles = UsePartFiles,
        YouTubeSponsorBlock = YouTubeSponsorBlock,
        SpeedLimit = SpeedLimit,
        ProxyUrl = ProxyUrl,
        CookiesBrowser = CookiesBrowser,
        CookiesPath = CookiesPath,
        EmbedMetadata = EmbedMetadata,
        RemoveSourceData = RemoveSourceData,
        EmbedThumbnails = EmbedThumbnails,
        CropAudioThumbnails = CropAudioThumbnails,
        EmbedChapters = EmbedChapters,
        EmbedSubtitles = EmbedSubtitles,
        PostprocessingThreads = PostprocessingThreads,
        PostprocessingArguments = PostprocessingArguments,
        UseAria = UseAria,
        AriaMaxConnectionsPerServer = AriaMaxConnectionsPerServer,
        AriaMinSplitSize = AriaMinSplitSize,
        YtdlpDiscoveryArgs = YtdlpDiscoveryArgs,
        YtdlpDownloadArgs = YtdlpDownloadArgs
    };

    [JsonConverter(typeof(NullToZeroIntConverter))]
    public int MaxNumberOfActiveDownloads
    {
        get => field == 0 ? 5 : field;

        set;
    }

    [JsonConverter(typeof(NullToZeroIntConverter))]
    public int PostprocessingThreads
    {
        get => field == 0 ? Environment.ProcessorCount : field;

        set;
    }

    [JsonConverter(typeof(NullToZeroIntConverter))]
    public int AriaMaxConnectionsPerServer
    {
        get => field == 0 ? 16 : field;

        set;
    }

    [JsonConverter(typeof(NullToZeroIntConverter))]
    public int AriaMinSplitSize
    {
        get => field == 0 ? 20 : field;

        set;
    }

    public override string ToString() => JsonSerializer.Serialize(this, _options);
}
