using System;
using System.Collections.Generic;

namespace Nickvision.Parabolic.Shared.Models;

public class DownloaderOptions
{
    public int MaxNumberOfActiveDownloads { get; set; }
    public bool OverwriteExistingFiles { get; set; }
    public bool LimitCharacters { get; set; }
    public bool IncludeMediaIdInTitle { get; set; }
    public bool IncludeAutoGeneratedSubtitles { get; set; }
    public VideoCodec PreferredVideoCodec { get; set; }
    public AudioCodec PreferredAudioCodec { get; set; }
    public SubtitleFormat PreferredSubtitleFormat { get; set; }
    public bool UsePartFiles { get; set; }
    public bool YouTubeSponsorBlock { get; set; }
    public int? SpeedLimit { get; set; }
    public string ProxyUrl { get; set; }
    public Browser CookiesBrowser { get; set; }
    public string CookiesPath { get; set; }
    public bool EmbedMetadata { get; set; }
    public bool RemoveSourceData { get; set; }
    public bool EmbedThumbnails { get; set; }
    public bool CropAudioThumbnails { get; set; }
    public bool EmbedChapters { get; set; }
    public bool EmbedSubtitles { get; set; }
    public int PostprocessingThreads { get; set; }
    public List<PostProcessorArgument> PostprocessingArguments { get; set; }
    public bool UseAria { get; set; }
    public int AriaMaxConnectionsPerServer { get; set; }
    public int AriaMinSplitSize { get; set; }
    public string YtdlpDiscoveryArgs { get; set; }
    public string YtdlpDownloadArgs { get; set; }

    public DownloaderOptions()
    {
        MaxNumberOfActiveDownloads = 5;
        OverwriteExistingFiles = true;
        LimitCharacters = OperatingSystem.IsWindows();
        IncludeMediaIdInTitle = true;
        IncludeAutoGeneratedSubtitles = true;
        PreferredVideoCodec = VideoCodec.Any;
        PreferredAudioCodec = AudioCodec.Any;
        PreferredSubtitleFormat = SubtitleFormat.Any;
        UsePartFiles = true;
        YouTubeSponsorBlock = false;
        SpeedLimit = null;
        ProxyUrl = string.Empty;
        CookiesBrowser = Browser.None;
        CookiesPath = string.Empty;
        EmbedMetadata = true;
        RemoveSourceData = false;
        EmbedThumbnails = true;
        CropAudioThumbnails = false;
        EmbedChapters = false;
        EmbedSubtitles = true;
        PostprocessingThreads = Environment.ProcessorCount;
        PostprocessingArguments = new List<PostProcessorArgument>();
        UseAria = false;
        AriaMaxConnectionsPerServer = 16;
        AriaMinSplitSize = 20;
        YtdlpDiscoveryArgs = string.Empty;
        YtdlpDownloadArgs = string.Empty;
    }

    public override int GetHashCode() => HashCode.Combine(
        HashCode.Combine(MaxNumberOfActiveDownloads, OverwriteExistingFiles, LimitCharacters, IncludeMediaIdInTitle, IncludeAutoGeneratedSubtitles, PreferredVideoCodec, PreferredVideoCodec, PreferredSubtitleFormat),
        HashCode.Combine(UsePartFiles, YouTubeSponsorBlock, SpeedLimit, ProxyUrl, CookiesBrowser, CookiesPath, EmbedMetadata, RemoveSourceData),
        HashCode.Combine(EmbedThumbnails, CropAudioThumbnails, EmbedChapters, EmbedSubtitles, PostprocessingThreads, UseAria, AriaMaxConnectionsPerServer, YtdlpDiscoveryArgs),
        YtdlpDownloadArgs,
        AriaMinSplitSize);
}
