name: tube-converter 
base: core24
adopt-info: tube-converter
grade: stable
confinement: strict
compression: lzo

lint:
  ignore:
    - classic
    - library

parts:
  gtk4:
    source: https://gitlab.gnome.org/GNOME/gtk.git
    source-tag: '4.19.4'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Dbuildtype=release
      - -Dbroadway-backend=true
      - -Dx11-backend=true
      - -Dwayland-backend=true
      - -Dwin32-backend=false
      - -Dmacos-backend=false
      - -Dintrospection=enabled
      - -Ddocumentation=false
      - -Dbuild-examples=false
      - -Dbuild-tests=false
      - -Dmedia-gstreamer=enabled
      - -Dbuild-demos=false
      - -Dbuild-testsuite=false
      - -Dbuild-examples=false
      - -Dbuild-tests=false
      - -Dprint-cups=enabled
      - -Dc_args=['-Wno-error=redundant-decls', '-Wno-redundant-decls']
    organize:
      usr/lib/gtk-4.0: usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gtk-4.0
    build-packages:
      - libxkbcommon-dev
      - libcups2-dev
      - libcolord-dev
      - libxrandr-dev
      - libxcursor-dev
      - libxcomposite-dev
      - libxdamage-dev
      - libxfixes-dev
      - libxi-dev
      - libxkbfile-dev
      - libxml2-utils
      - libgstreamer-plugins-bad1.0-dev
      - libvulkan-dev
      - libwayland-dev
      - glslc
      - gcc-multilib
      - libgraphene-1.0-dev

  libadwaita:
    after: [gtk4]
    source: https://gitlab.gnome.org/GNOME/libadwaita.git
    source-tag: '1.8.1'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Dbuildtype=release
      - -Dintrospection=enabled
      - -Dvapi=true
      - -Dgtk_doc=false
      - -Dtests=false
      - -Dexamples=false
      - -Dc_args="-Wno-error=format-nonliteral"
    build-environment:
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$PKG_CONFIG_PATH
    build-packages:
      - sassc
      - libyaml-dev
      - libzstd-dev
      - libsystemd-dev
      - gperf
      - libappstream-dev
      - glslc

  deps:
    plugin: nil
    stage-packages:
      - libstdc++6
      - aria2
      - libcares2
      - libaria2-0
      - libboost-system1.83.0
      - libboost-date-time1.83.0
      - libboost-json1.83.0
      - libsqlcipher-dev
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libstdc++*.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libaria2.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libcares.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_system.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_date_time.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_json.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libsqlcipher.so*
      - usr/bin/aria2c

  python-deps:
    plugin: python
    source: .
    python-packages:
      - yt-dlp[default,curl-cffi]==2025.11.12
      - mutagen
    stage:
      - -bin/activate*
      - -bin/Activate.ps1
      - -bin/python*
      - -bin/pip*
      - -pyvenv.cfg
      - -lib/*/*/setup*
      - -lib/*/*/pkg*
      - -lib/*/*/pip*
      - -lib/*/*/_dist*
      - -share
      - -include
    organize:
      lib/python3.12/site-packages: usr/lib/python3/dist-packages

  cpr:
    source: https://github.com/libcpr/cpr.git
    source-commit: 'a0ff651296a620ed5fabf7d12cf4905fefc7ce86'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCPR_BUILD_TESTS=OFF
      - -DCPR_USE_SYSTEM_CURL=ON
      - -DCPR_ENABLE_SSL=ON
    override-prime: ''

  maddy:
    source: https://github.com/progsource/maddy.git
    source-tag: '1.6.0'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-prime: ''

  libnick:
    after: [cpr, maddy]
    source: https://github.com/NickvisionApps/libnick.git
    source-tag: '2025.10.0'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DCMAKE_BUILD_TYPE=Release
    build-environment:
      - CMAKE_PREFIX_PATH: ${CRAFT_STAGE}/usr${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
    build-packages:
      - libssl-dev
      - uuid-dev
      - libboost-dev
      - libboost-system1.83-dev
      - libboost-json1.83-dev
      - libsqlcipher-dev
    override-prime: ''

  deno:
    source: https://github.com/denoland/deno_install.git
    source-tag: 'v0.3.3'
    source-depth: 1
    plugin: dump
    build-packages:
      - unzip
      - curl
    override-build: |
      export DENO_INSTALL=/usr
      ./install.sh

  libxmlplusplus:
    source: https://github.com/libxmlplusplus/libxmlplusplus.git
    source-tag: '5.4.0'
    source-depth: 1
    plugin: meson
    build-packages:
      - libicu-dev
    meson-parameters:
      - --prefix=/usr
      - -Dmaintainer-mode=false
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libxml++-5.0*.so*

  tube-converter:
    after: [libadwaita, maddy, libnick, deno, libxmlplusplus]
    plugin: cmake
    source: .
    build-snaps:
      - cmake
      - ffmpeg-2404/latest/candidate
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/snap/tube-converter/current/usr
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - blueprint-compiler
      - libboost-dev
      - libboost-date-time1.83-dev
      - libboost-system1.83-dev
    stage-packages:
      - libstdc++6
    build-environment:
      - GI_TYPELIB_PATH: ${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/girepository-1.0:${GI_TYPELIB_PATH}
      - PKG_CONFIG_PATH: ${CRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$PKG_CONFIG_PATH
      - CMAKE_PREFIX_PATH: ${CRAFT_STAGE}/usr${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
    parse-info: [usr/share/metainfo/org.nickvision.tubeconverter.metainfo.xml]
    organize:
      snap/tube-converter/current: .

plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

slots:
  tube-converter:
    interface: dbus
    bus: session
    name: org.nickvision.tubeconverter

apps:
  tube-converter:
    command: usr/bin/org.nickvision.tubeconverter
    extensions:
      - gnome
    common-id: org.nickvision.tubeconverter
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
    plugs:
      - home
      - network
      - network-status
      - mount-observe
      - unity7
      - screen-inhibit-control
      - password-manager-service
