name: tube-converter # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: tube-converter
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

layout:
  $SNAP/usr/bin/ffmpeg:
    symlink: $SNAP/ffmpeg-platform/usr/bin/ffmpeg
  $SNAP/usr/bin/ffplay:
    symlink: $SNAP/ffmpeg-platform/usr/bin/ffplay
  $SNAP/usr/bin/ffprobe:
    symlink: $SNAP/ffmpeg-platform/usr/bin/ffprobe
parts:
  yt-dlp:
    # Missing optional dependencies atomicparsley, mpv, phantomjs and rtmpdump
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp.git
    source-tag: '2023.03.04'
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    python-packages:
      - psutil==5.9.5
    prime:
      # WORKAROUND: Skip venv from python plugin
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.10
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.10
      - -usr/bin/wheel
      - -usr/lib/python3.10/dist-packages/pip*
      - -usr/lib/python3.10/dist-packages/pkg_resources
      - -usr/lib/python3.10/dist-packages/setuptools*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
      - -share
    organize:
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3.10/dist-packages

  tube-converter:
    after: [ yt-dlp ]
    plugin: nil
    source: https://github.com/NickvisionApps/Parabolic.git
    source-tag: '2023.6.3'
    source-depth: 1
    build-packages:
      - brotli
      - blueprint-compiler
      - wget
    override-pull: |
      craftctl default
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 7.0
      patch -p1 < $CRAFT_PROJECT_DIR/snap/tube-converter.patch
    override-build: |
      set -eux
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
      cd $CRAFT_PART_SRC
      dotnet tool restore
      dotnet cake --target=Publish --prefix=/snap/tube-converter/current/usr --ui=gnome --self-contained
      dotnet cake --target=Install --destdir=$CRAFT_PART_INSTALL
      sed -i "2 i export TC_PYTHON_SO=\$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/libpython3.10.so.1.0" $CRAFT_PART_INSTALL/snap/tube-converter/current/usr/bin/org.nickvision.tubeconverter
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/tube-converter/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    prime:
      - -snap/tube-converter
    organize:
      snap/tube-converter/current: .
    parse-info: [usr/share/metainfo/org.nickvision.tubeconverter.metainfo.xml]
  deps:
    plugin: nil
    stage-packages:
      - aria2
      - libc-ares2
      - libaria2-0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/libaria2.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libaria2.so.0.0.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libcares.so.2
      - usr/lib/$CRAFT_ARCH_TRIPLET/libcares.so.2.5.1
      - usr/bin/aria2c

plugs:
  ffmpeg-2204:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2204
slots:
  # for GtkApplication registration
  tube-converter:
    interface: dbus
    bus: session
    name: org.nickvision.tubeconverter

apps:
  tube-converter:
    command: usr/bin/org.nickvision.tubeconverter
    extensions:
      - gnome
    common-id: org.nickvision.tubeconverter
    environment:
      TC_PYTHON_SO: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/libpython3.10.so.1.0
      PYTHONPATH: $SNAP/usr/lib/python3.10/dist-packages:$PYTHONPATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
    plugs:
      - home
      - network
      - network-status
      - mount-observe
      - unity7
