name: tube-converter 
base: core24
adopt-info: tube-converter
grade: stable
confinement: strict
compression: lzo

lint:
  ignore:
    - classic
    - library

parts:
  deps:
    plugin: nil
    stage-packages:
      - libstdc++6
      - aria2
      - libcares2
      - libaria2-0
      - libboost-system1.83.0
      - libboost-date-time1.83.0
      - libboost-json1.83.0
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libstdc++*.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libaria2.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libcares.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_system.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_date_time.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_json.so*
      - usr/bin/aria2c

  python-deps:
    plugin: python
    source: .
    python-packages:
      - yt-dlp==2025.02.19
    stage:
      - -bin/activate*
      - -bin/Activate.ps1
      - -bin/python*
      - -bin/pip*
      - -pyvenv.cfg
      - -lib/*/*/setup*
      - -lib/*/*/pkg*
      - -lib/*/*/pip*
      - -lib/*/*/_dist*
      - -share
      - -include
    organize:
      lib/python3.12/site-packages: usr/lib/python3/dist-packages

  maddy:
    source: https://github.com/progsource/maddy.git
    source-tag: '1.3.0'
    plugin: dump
    source-depth: 1
    override-prime: '' 

  libnick:
    after: [maddy]
    source: https://github.com/nickvisionapps/libnick.git
    source-tag: "2025.1.0"
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DCMAKE_BUILD_TYPE=Release
    build-environment:
      - CPLUS_INCLUDE_PATH: ${CRAFT_STAGE}/include
    build-packages:
      - libssl-dev
      - uuid-dev
      - libboost-dev
      - libboost-system1.83-dev
      - libboost-json1.83-dev
    override-prime: ''

  libxmlplusplus:
    source: https://github.com/libxmlplusplus/libxmlplusplus.git
    source-tag: '5.4.0'
    source-depth: 1
    plugin: meson
    build-packages:
      - libicu-dev
    meson-parameters:
      - --prefix=/usr
      - -Dmaintainer-mode=false
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libxml++-5.0*.so*

  tube-converter:
    after: [maddy, libnick, libxmlplusplus]
    plugin: cmake
    source: .
    build-snaps:
      - cmake
      - blueprint-compiler/latest/edge
      - ffmpeg-2404/latest/candidate
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/snap/tube-converter/current/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DUI_PLATFORM=gnome
    build-packages:
      - libboost-dev
      - libboost-date-time1.83-dev
      - libboost-system1.83-dev
    build-environment:
      - CMAKE_PREFIX_PATH: ${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/cmake${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
    parse-info: [usr/share/metainfo/org.nickvision.tubeconverter.metainfo.xml]
    organize:
      snap/tube-converter/current: .

plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

slots:
  tube-converter:
    interface: dbus
    bus: session
    name: org.nickvision.tubeconverter

apps:
  tube-converter:
    command: usr/bin/org.nickvision.tubeconverter
    extensions:
      - gnome
    common-id: org.nickvision.tubeconverter
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
    plugs:
      - home
      - network
      - network-status
      - mount-observe
      - unity7
      - screen-inhibit-control
      - password-manager-service
