on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Test
permissions:
  id-token: write
  contents: read
env:
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
jobs:
  windows:
    name: "Test on Windows"
    runs-on: windows-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Setup Environment"
        run: |
          mkdir build
          choco install ffmpeg
          choco install aria2
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: boost-date-time libnick
          triplet: x64-windows
          revision: 02d93df47bb4c9b062921b26c77a251490127151
          token: ${{ secrets.GITHUB_TOKEN }}
          github-binarycache: true
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -G "Visual Studio 17 2022" .. -DBUILD_TESTING=ON -DBACKEND_ONLY=ON
          cmake --build . --config Release
      - name: Test
        run: ${{github.workspace}}/build/libparabolic/Release/libparabolic_test.exe
